export const origin = ["Science", "Mutation", "Magic", "Technology", "Natural"];

export const playStyles = [
  "Tank",
  "Melee Damage",
  "Ranged Damage",
  "Crowd Control",
  "Support",
  "Pets",
];

export const playStyleArchs = {
  Tank: ["Brute", "Tanker"],
  "Melee Damage": ["Brute", "Scrapper", "Stalker", "Tanker"],
  "Ranged Damage": ["Blaster", "Corruptor", "Defender", "Sentinal"],
  "Crowd Control": ["Controller", "Dominator"],
  Support: ["Controller", "Corruptor", "Defender", "Mastermind"],
  Pets: ["Controller", "Dominator", "Mastermind"],
};

export const brute = {
  primary: [
    "Battle Axe",
    "Board Sword",
    "Claws",
    "Dark Melee",
    "Dual Blades",
    "Electrical Melee",
    "Energy Melee",
    "Fiery Melee",
    "Ice Melee",
    "Katana",
    "Kenetic Melee",
    "Martial Arts",
    "Psionic Melee",
    "Radiation Melee",
    "Savage Melee",
    "Spines",
    "Staff Fighting",
    "Stone Melee",
    "Street Justice",
    "Super Strength",
    "Titian Weapons",
    "War Mace",
  ],
  secondary: [
    "Bio Armor",
    "Dark Armor",
    "Electric Armor",
    "Energy Aura",
    "Fiery Aura",
    "Ice Armor",
    "Invulnerability",
    "Radiation Armor",
    "Regeneration",
    "Shield Defense",
    "Stone Armor",
    "Super Reflexes",
    "Willpower",
  ],
};
export const blaster = {
  primary: [
    "Archery",
    "Assult Rifle",
    "Beam Rifle",
    "Dark Blast",
    "Dual Pistols",
    "Electrical Blast",
    "Energy Blast",
    "Fire Blast",
    "Ice Blast",
    "Psychic Blast",
    "Radiation Blast",
    "Seismic Blast",
    "Sonic Attack",
    "Storm Blast",
    "Water Blast",
  ],
  secondary: [
    "Atomic Manipulation",
    "Darkness Manipulation",
    "Devices",
    "Earth Manipulation",
    "Electricity Manipulation",
    "Energy Manipulation",
    "Fire Manipulation",
    "Ice Manipulation",
    "Martial Combat",
    "Mental Manipulation",
    "Ninja Training",
    "Plant Manipulation",
    "Sonic Manipulation",
    "Tactical Arrow",
    "Temporal Manipulation",
  ],
};

export const controller = {
  primary: [
    "Arsenal Control",
    "Darkness Control",
    "Earth Control",
    "Electric Control",
    "Fire Control",
    "Gravity Control",
    "Ice Control",
    "Illusion Control",
    "Mind Control",
    "Plant Control",
    "Symphony Control",
  ],
  secondary: [
    "Cold Domination",
    "Darkness Affinity",
    "Electrical Affinity",
    "Empathy",
    "Force Field",
    "Kinetics",
    "Marine Affinity",
    "Nature Affinity",
    "Pain Domination",
    "Poison",
    "Radiation Emission",
    "Sonic Resonance",
    "Storm Summoning",
    "Thermal Radiation",
    "Time Manipulation",
    "Traps",
    "Trick Arrow",
  ],
};

export const corruptor = {
  primary: [
    "Archery",
    "Assult Rifle",
    "Beam Rifle",
    "Dark Blast",
    "Dual Pistols",
    "Electrical Blast",
    "Energy Blast",
    "Fire Blast",
    "Ice Blast",
    "Psychic Blast",
    "Radiation Blast",
    "Seismic Blast",
    "Sonic Attack",
    "Storm Blast",
    "Water Blast",
  ],
  secondary: [
    "Cold Domination",
    "Dark Miasma",
    "Electrical Affinity",
    "Empathy",
    "Force Field",
    "Kinetics",
    "Marine Affinity",
    "Nature Affinity",
    "Pain Domination",
    "Poison",
    "Radiation Emission",
    "Sonic Resonance",
    "Storm Summoning",
    "Thermal Radiation",
    "Time Manipulation",
    "Traps",
    "Trick Arrow",
  ],
};

export const defender = {
  primary: [
    "Cold Domination",
    "Dark Miasma",
    "Electrical Affinity",
    "Empathy",
    "Force Field",
    "Kinetics",
    "Marine Affinity",
    "Nature Affinity",
    "Pain Domination",
    "Poison",
    "Radiation Emission",
    "Sonic Resonance",
    "Storm Summoning",
    "Thermal Radiation",
    "Time Manipulation",
    "Traps",
    "Trick Arrow",
  ],
  secondary: [
    "Archery",
    "Assult Rifle",
    "Beam Rifle",
    "Dark Blast",
    "Dual Pistols",
    "Electrical Blast",
    "Energy Blast",
    "Fire Blast",
    "Ice Blast",
    "Psychic Blast",
    "Radiation Blast",
    "Seismic Blast",
    "Sonic Attack",
    "Storm Blast",
    "Water Blast",
  ],
};

export const tanker = {
  primary: [
    "Bio Armor",
    "Dark Armor",
    "Electric Armor",
    "Fiery Aura",
    "Ice Armor",
    "Invulnerability",
    "Radiation Armor",
    "Shield Defense",
    "Stone Armor",
    "Super Reflexes",
    "Willpower",
  ],
  secondary: [
    "Battle Axe",
    "Board Sword",
    "Claws",
    "Dark Melee",
    "Dual Blades",
    "Electrical Melee",
    "Energy Melee",
    "Fiery Melee",
    "Ice Melee",
    "Katana",
    "Kenetic Melee",
    "Martial Arts",
    "Psionic Melee",
    "Radiation Melee",
    "Savage Melee",
    "Spines",
    "Staff Fighting",
    "Stone Melee",
    "Street Justice",
    "Super Strength",
    "Titian Weapons",
    "War Mace",
  ],
};

export const scrapper = {
  primary: [
    "Battle Axe",
    "Board Sword",
    "Claws",
    "Dark Melee",
    "Dual Blades",
    "Electrical Melee",
    "Energy Melee",
    "Fiery Melee",
    "Ice Melee",
    "Katana",
    "Kenetic Melee",
    "Martial Arts",
    "Psionic Melee",
    "Radiation Melee",
    "Savage Melee",
    "Spines",
    "Staff Fighting",
    "Stone Melee",
    "Street Justice",
    "Super Strength",
    "Titian Weapons",
    "War Mace",
  ],
  secondary: [
    "Bio Armor",
    "Dark Armor",
    "Electric Armor",
    "Energy Aura",
    "Fiery Aura",
    "Ice Armor",
    "Invulnerability",
    "Ninjitsu",
    "Radiation Armor",
    "Regeneration",
    "Shield Defense",
    "Stone Armor",
    "Super Reflexes",
    "Willpower",
  ],
};

export const dominator = {
  primary: [
    "Arsenal Control",
    "Darkness Control",
    "Earth Control",
    "Electric Control",
    "Fire Control",
    "Gravity Control",
    "Ice Control",
    "Illusion Control",
    "Mind Control",
    "Plant Control",
    "Symphony Control",
  ],
  secondary: [
    "Arsenal Assault",
    "Dark Assault",
    "Earth Assault",
    "Electricity Assault",
    "Energy Assault",
    "Fiery Assault",
    "Icy Assault",
    "Martial Assault",
    "Psionic Assault",
    "Radioactive Assault",
    "Savage Assault",
    "Sonic Assault",
    "Thorny Assault",
  ],
};

export const stalker = {
  primary: [
    "Board Sword",
    "Claws",
    "Dark Melee",
    "Dual Blades",
    "Electrical Melee",
    "Energy Melee",
    "Fiery Melee",
    "Ice Melee",
    "Kenetic Melee",
    "Martial Arts",
    "Ninja Blade",
    "Psionic Melee",
    "Radiation Melee",
    "Savage Melee",
    "Spines",
    "Staff Fighting",
    "Stone Melee",
    "Street Justice",
  ],
  secondary: [
    "Bio Armor",
    "Dark Armor",
    "Electric Armor",
    "Energy Aura",
    "Fiery Aura",
    "Ice Armor",
    "Invulnerability",
    "Ninjitsu",
    "Radiation Armor",
    "Regeneration",
    "Shield Defense",
    "Stone Armor",
    "Super Reflexes",
    "Willpower",
  ],
};
export const sentinal = {
  primary: [
    "Archery",
    "Assult Rifle",
    "Beam Rifle",
    "Dark Blast",
    "Dual Pistols",
    "Electrical Blast",
    "Energy Blast",
    "Fire Blast",
    "Ice Blast",
    "Psychic Blast",
    "Radiation Blast",
    "Seismic Blast",
    "Sonic Attack",
    "Storm Blast",
    "Water Blast",
  ],
  secondary: [
    "Bio Armor",
    "Dark Armor",
    "Electric Armor",
    "Energy Aura",
    "Fiery Aura",
    "Ice Armor",
    "Invulnerability",
    "Ninjitsu",
    "Radiation Armor",
    "Regeneration",
    "Stone Armor",
    "Super Reflexes",
    "Willpower",
  ],
};

export const mastermind = {
  primary: [
    "Beast Mastery",
    "Demon Summoning",
    "Mercenaries",
    "Necromancy",
    "Ninjas",
    "Robotics",
    "Thugs",
  ],
  secondary: [
    "Cold Domination",
    "Dark Miasma",
    "Electrical Affinity",
    "Empathy",
    "Force Field",
    "Kinetics",
    "Marine Affinity",
    "Nature Affinity",
    "Pain Domination",
    "Poison",
    "Radiation Emission",
    "Sonic Resonance",
    "Storm Summoning",
    "Thermal Radiation",
    "Time Manipulation",
    "Traps",
    "Trick Arrow",
  ],
};
